services:
  paugo-api:
    restart: always
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    networks:
      - api

  postgres:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d $DB_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql@16/data
    ports:
      - "5432:5432"
    networks:
      - api

  migrations:
    build:
      dockerfile: Dockerfile
      context: internal/database/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: ${GOOSE_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - api

volumes:
  pg_data:

networks:
  api:
    driver: bridge
