name: Deploy dev

on:
  push:
    branches:
      - develop

jobs:
  dockerize:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Build and push api image
        id: build-api
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}/api:latest

      - name: Build and push migrations
        id: build-migrations
        uses: docker/build-push-action@v6
        with:
          context: ./internal/database/migrations
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}/migrations:latest
